version: "3.8"

services:
  
  postgres:
   image: postgres
   restart: always
   ports:
     - "5431:5432"
   environment:
    DATABASE_HOST: 126.0.0.1
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    POSTGRES_DB: root

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"

  

